ADMINS = ['flask.boilerplate@gmail.com']
ADMIN_CREDENTIALS = ('admin', 'pa$$word')
BCRYPT_LOG_ROUNDS = 12 # number of times a password is hashed
MAIL_PASSWORD = 'flaskboilerplate123'
MAIL_PORT = 465
MAIL_SERVER = 'smtp.googlemail.com'
MAIL_USE_SSL = True
MAIL_USE_TLS = False
MAIL_USERNAME = 'flask.boilerplate'
SECRET_KEY = 'houdini' # secret key for generating tokens
SQLALCHEMY_DATABASE_URI = 'sqlite:///app.db'
SQLALCHEMY_TRACK_MODIFICATIONS = True
TIMEZONE = 'Europe/Paris'
